export const easyConfig= {
    "gameSettings":
        {
            "startingDirection":"NORTH",
            "startingFlashLightOn":false,
            "startingCurrentRoomNumber":1,
            "startingGoldCount":0,
            "secondsNeeded":300
        },
    "items":
        [
            {
                "itemType":"GOLD",
                "wallDirection":"WEST",
                "roomNumber":1,
                "goldCount":20,
                "keyId":0,
                "price":0
            },
            {
                "itemType":"FLASHLIGHT",
                "wallDirection":"WEST",
                "roomNumber":1,
                "goldCount":0,
                "keyId":0,
                "price":0
            },
            {
                "itemType":"KEY",
                "wallDirection":"NORTH",
                "roomNumber":2,
                "goldCount":0,
                "keyId":2,
                "price":15
            }
        ],
    "rooms":
        [
            {
                "roomNumber":1,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":2,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
        
            },
            {
                "roomNumber":3,
                "thereLight":true,
                "lightOn":true,
                "endRoom":true
            }
        ],

    "walls":
        [ 
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":1,
                "hiddenKeyId":0,
                "room1Number":1,
                "room2Number":2,
                "roomNumber":1,
                "wallDirection":"EAST"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":2,
                "hiddenKeyId":0,
                "room1Number":2,
                "room2Number":3,
                "roomNumber":2,
                "wallDirection":"EAST"
            },
            {
                "wallType":"SELLER",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":2,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"CHEST",
                "locked":true,
                "lockingKeyId":3,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":1,
                "wallDirection":"WEST"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":1,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":1,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"PAINTING",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":3,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":1,
                "wallDirection":"SOUTH"
            }
        ]
}

export const mediumConfig={
    "gameSettings":
        {
            "startingDirection":"NORTH",
            "startingFlashLightOn":false,
            "startingCurrentRoomNumber":1,
            "startingGoldCount":0,
            "secondsNeeded":900
        },
    "rooms":
        [
            {
                "roomNumber":1,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":2,
                "thereLight":true,
                "lightOn":false,
                "endRoom":false
        
            },
            {
                "roomNumber":3,
                "thereLight":false,
                "lightOn":false,
                "endRoom":false
            },
            {
                "roomNumber":4,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":5,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":6,
                "thereLight":true,
                "lightOn":true,
                "endRoom":true
            }
        ],
    "walls":
        [ 
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":1,
                "hiddenKeyId":0,
                "room1Number":1,
                "room2Number":3,
                "roomNumber":1,
                "wallDirection":"EAST"
            },
            {
                "wallType":"PAINTING",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":1,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":1,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"DOOR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":1,
                "room2Number":2,
                "roomNumber":1,
                "wallDirection":"SOUTH"
            },
            {
                "wallType":"DOOR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":2,
                "room2Number":4,
                "roomNumber":2,
                "wallDirection":"EAST"
            },
            {
                "wallType":"CHEST",
                "locked":true,
                "lockingKeyId":2,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":2,
                "wallDirection":"WEST"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":3,
                "hiddenKeyId":0,
                "room1Number":3,
                "room2Number":6,
                "roomNumber":3,
                "wallDirection":"EAST"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":4,
                "hiddenKeyId":0,
                "room1Number":4,
                "room2Number":5,
                "roomNumber":4,
                "wallDirection":"EAST"
            },
            {
                "wallType":"SELLER",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":4,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":2,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":4,
                "wallDirection":"SOUTH"
            },
            {
                "wallType":"CHEST",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":5,
                "wallDirection":"EAST"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":5,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"PAINTING",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":5,
                "wallDirection":"SOUTH"
            }
        ],
        "items":
        [
            {
                "itemType":"GOLD",
                "wallDirection":"WEST",
                "roomNumber":2,
                "goldCount":10,
                "keyId":0,
                "price":0
            },
            {
                "itemType":"FLASHLIGHT",
                "wallDirection":"NORTH",
                "roomNumber":4,
                "goldCount":0,
                "keyId":0,
                "price":5
            },
            {
                "itemType":"KEY",
                "wallDirection":"NORTH",
                "roomNumber":4,
                "goldCount":0,
                "keyId":4,
                "price":5
            },
            {
                "itemType":"KEY",
                "wallDirection":"EAST",
                "roomNumber":5,
                "goldCount":0,
                "keyId":3,
                "price":0
            },
        ]
};

export const hardConfig={
    "gameSettings":
        {
            "startingDirection":"EAST",
            "startingFlashLightOn":false,
            "startingCurrentRoomNumber":1,
            "startingGoldCount":20,
            "secondsNeeded":1800
        },
    "rooms":
        [
            {
                "roomNumber":1,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":2,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
        
            },
            {
                "roomNumber":3,
                "thereLight":true,
                "lightOn":false,
                "endRoom":false
            },
            {
                "roomNumber":4,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":5,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":6,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":7,
                "thereLight":false,
                "lightOn":false,
                "endRoom":false
            },
            {
                "roomNumber":8,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":9,
                "thereLight":true,
                "lightOn":true,
                "endRoom":false
            },
            {
                "roomNumber":10,
                "thereLight":true,
                "lightOn":true,
                "endRoom":true
            }
        ],
    "walls":
        [ 
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":3,
                "hiddenKeyId":0,
                "room1Number":1,
                "room2Number":4,
                "roomNumber":1,
                "wallDirection":"EAST"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":6,
                "hiddenKeyId":0,
                "room1Number":1,
                "room2Number":9,
                "roomNumber":1,
                "wallDirection":"WEST"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":1,
                "hiddenKeyId":0,
                "room1Number":1,
                "room2Number":2,
                "roomNumber":1,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"PAINTING",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":1,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":1,
                "wallDirection":"SOUTH"
            },
            {
                "wallType":"DOOR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":2,
                "room2Number":3,
                "roomNumber":2,
                "wallDirection":"EAST"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":2,
                "wallDirection":"WEST"
            },
            {
                "wallType":"CHEST",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":2,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":2,
                "hiddenKeyId":0,
                "room1Number":3,
                "room2Number":10,
                "roomNumber":3,
                "wallDirection":"EAST"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":3,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"DOOR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":4,
                "room2Number":5,
                "roomNumber":4,
                "wallDirection":"EAST"
            },
            {
                "wallType":"CHEST",
                "locked":true,
                "lockingKeyId":7,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":4,
                "wallDirection":"SOUTH"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":4,
                "hiddenKeyId":0,
                "room1Number":5,
                "room2Number":7,
                "roomNumber":5,
                "wallDirection":"EAST"
            },
            {
                "wallType":"SELLER",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":5,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"DOOR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":5,
                "room2Number":6,
                "roomNumber":5,
                "wallDirection":"SOUTH"
            },
            {
                "wallType":"PAINTING",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":6,
                "wallDirection":"EAST"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":7,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":6,
                "wallDirection":"WEST"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":6,
                "wallDirection":"SOUTH"
            },
            {
                "wallType":"CHEST",
                "locked":false,
                "lockingKeyId":8,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":7,
                "wallDirection":"EAST"
            },
            {
                "wallType":"DOOR",
                "locked":true,
                "lockingKeyId":5,
                "hiddenKeyId":0,
                "room1Number":7,
                "room2Number":8,
                "roomNumber":7,
                "wallDirection":"NORTH"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":7,
                "wallDirection":"SOUTH"
            },
            {
                "wallType":"MIRROR",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":8,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":8,
                "wallDirection":"WEST"
            },
            {
                "wallType":"PAINTING",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":0,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":9,
                "wallDirection":"WEST"
            },
            {
                "wallType":"PAINTING",
                "locked":false,
                "lockingKeyId":0,
                "hiddenKeyId":2,
                "room1Number":0,
                "room2Number":0,
                "roomNumber":9,
                "wallDirection":"NORTH"
            }
        ],
        "items":
        [
            {
                "itemType":"KEY",
                "wallDirection":"NORTH",
                "roomNumber":2,
                "goldCount":0,
                "keyId":3,
                "price":0
            },
            {
                "itemType":"FLASHLIGHT",
                "wallDirection":"SOUTH",
                "roomNumber":4,
                "goldCount":0,
                "keyId":0,
                "price":0
            },
            {
                "itemType":"FLASHLIGHT",
                "wallDirection":"NORTH",
                "roomNumber":5,
                "goldCount":0,
                "keyId":0,
                "price":7
            },
            {
                "itemType":"KEY",
                "wallDirection":"NORTH",
                "roomNumber":5,
                "goldCount":0,
                "keyId":5,
                "price":25
            },
            {
                "itemType":"KEY",
                "wallDirection":"NORTH",
                "roomNumber":5,
                "goldCount":0,
                "keyId":4,
                "price":0
            },
            {
                "itemType":"KEY",
                "wallDirection":"EAST",
                "roomNumber":7,
                "goldCount":0,
                "keyId":6,
                "price":0
            },
            {
                "itemType":"GOLD",
                "wallDirection":"EAST",
                "roomNumber":7,
                "goldCount":3,
                "keyId":0,
                "price":0
            },
        ]
};
